### ISSUE TITLE
warn message about restart will reset

### ISSUE THREAD

**Issue by DcFamas** [MiSchroe/ioBroker.klf200#100]
Hey there,
I'm using a script which messages me via. Signal, when something is wrong with ioBroker. The script checks the log entries.
Everyday the adapter creates this log entry:

<html><body>

klf200.0 | 2022-11-03 03:00:02.245 | warn | Restart initiated
-- | -- | -- | --

</body>
</html>

When I change the log level of the instance, it will get resettet after a day. How is it possible to either change the log level or the log entry itself?

Thank you and best regards :)

**Comment by MiSchroe** [comment]
It seems that you restart the gateway or the adapter at 3am. You can change the log level in the advanced view of the instances.
<img width="607" alt="image" src="https://user-images.githubusercontent.com/14166812/199685887-9e5eec4d-61cc-444f-940c-9cd451f16e96.png">

**Comment by DcFamas** [comment]
Hey @MiSchroe that is the main problem. When I change the _Log level_ it will changed every night, only for this adapter.
