### ISSUE TITLE
targetPosition reversed

### ISSUE THREAD

**Issue by xxxNASHxxx** [MiSchroe/ioBroker.klf200#110]
Hi. 
I think the open-close position are wrong.
Velux says, 100% are complet open and 0% are complete closed.
I use Alexa to move the Roller Shutters. When I say A..., Roller Shutter open the setpoint changes to 100% but the Shutters shut down.
Can you fix this please?
thanks.

**Comment by MiSchroe** [comment]
The implementation follows the API documentation:
![image](https://user-images.githubusercontent.com/14166812/213131413-fcbb2c67-a062-48f6-93b5-84e71b5932f9.png)
Though I see your point a change of the behaviour would break many existing installations. As an alternative you could create an alias. See https://www.iobroker.net/#en/documentation/dev/aliases.md.
