### ISSUE TITLE
Flüstermodus ohne Szenen

### ISSUE THREAD

**Issue by Mathias86KNX** [MiSchroe/ioBroker.klf200#111]
Hallo lieber Entwickler,

ich habe den Adapter erfolgreich im Einsatz. Vielen Dank dafür. Ich kann den Flüstermodus nur mit Szenen verwenden. Gibt es eine Möglichkeit den Flüstermodus auch ohne Szenen zu verwenden? Dies wäre für meine automatische Beschattung echt toll, denn ich könnte das Rollo absolut anfahren und bräuchte nicht immer Szenen...

Vielen Dank und viele Grüße
Mathias

**Comment by MiSchroe** [comment]
Duplicate of #77
