### ISSUE TITLE
Einstellungen laden mit Fehler

### ISSUE THREAD

**Issue by Zinski** [MiSchroe/ioBroker.klf200#114]
Ich habe schon länger wirklich Probleme damit, diesen Adapter richtig ans laufen zu bekommen. Er lief bisher und nach einem Update des ioBrokers geht nichts mehr. Leider kann ich die Konfiguration des Adapters nicht mehr ändern, sobald ich ihn initial konfiguriert habe.

**To Reproduce**  
Ich weiß leider nicht, ob es sich reproduzieren lässt, jedoch bin ich verzweifelt, da ich gerade weder Rollos noch Fenster steuern kann.

**Expected behavior**  
Eingabemaske wie bei initialer Konfiguration nach Installation des Adapters

**Screenshots & Logfiles**  
So sieht der Konfigurationsscreen bei mir aus. Das deutet für mich daraufhin, dass es ein Problem beim Laden des Screens gibt, ich kann aber nichts im Log des Adapters oder ioBrokers sehen.
![Bildschirmfoto 2023-09-15 um 09 52 40](https://github.com/MiSchroe/ioBroker.klf200/assets/8176856/1bb39daf-bfce-4bf7-8076-ed3c431bd16a)

**Versions:**  
 - Adapter version: 1.0.1
 - JS-Controller version: 5.0.12
 - Node version:18.17.1
 - Operating system: Docker Container, tag latest-v8 auf einem Raspberry Pi

**Comment by StinkyHeXoR** [comment]
Ich kann jetzt leider nicht meine Konfiguration teilen, aber ich habe seit knapp zwei Wochen ein ähnliches Problem. Ich hab letztes Wochenende alles schön nach Anleitung probiert, aber der Adapter verbindet nicht mehr.

**Comment by dekatWin** [comment]
Kenne das Problem ebenfalls, da hilft nur:

1. Adapter deinstallieren.
2. ganzen KLF200 Objekbaum unter Objekte löschen.
3.  Adapter neu installieren und einstellen.

Das fixed das Problem für mich, ist jedoch nur ein Workaround.
Ich vermute der Bug wird ausgelöst wenn ein bekanntes Velux Gerät auf Werkseinstellung gesetzt wird, wirklich belegen kann ich meine Vermutung jedoch net.

**Comment by StinkyHeXoR** [comment]
Danke für den Tip, mir hat es leider nicht geholfen.

**Comment by dekatWin** [comment]
Bitte deinstalliere den Adapter, gehe dann in das Iobroker-Verzeichnis und lade den Teil des Logs hoch, der entsteht, wenn du den Adapter neu installierst und zum ersten Mal konfigurierst, am besten direkt 2 Instanzen installieren und nicht nur eine.

**Comment by dekatWin** [comment]
Übrigend kann man auch ohne config index, Einstellungen setzen, die Einstellungen sind bei den Adaptern meist ebenfalls als objekt angelegt. ---->

![image](https://github.com/MiSchroe/ioBroker.klf200/assets/111662370/a1b8ea2c-6c23-43e1-b673-7a10e61adb28)

**Comment by dekatWin** [comment]
Ok, hab mir kurz angeschaut was genau mit der v5.0 geändert wurde,  
---> https://github.com/ioBroker/adapter-core#commontools

```
//neue dependency hinzufügen: 
npm i @iobroker/adapter-core
//tausche
const utils = require("./utils");
//gegen
const utils = require("@iobroker/adapter-core");
//evt. anpassen und erweitern weiterer tool exporte
```
---> controllerTools.js 

Ich vermute, dass der Doker Bug nur durch ein Update behoben werden kann, aber ich bin nur ein Hobby-Coder, also liegt es wahrscheinlich an etwas anderem.

**Comment by MiSchroe** [comment]
@Zinski , ich kann den Fehler nicht nachstellen. Ich habe gerade den latest-v8 Docker Container installiert (bei mir auf einer Windows-Maschine), dann den KLF-200-Adapter installiert. Anschließend habe ich ein Upgrade des JS-Controllers auf die neueste Version durchgeführt (5.0.12) und außerdem die aktuellste Admin-Version installiert (6.10.1).

Ich kann ganz normal die Konfiguration bearbeiten und speichern. Der Adapter verbindet sich bei mir auch mit dem KLF-200.
