### ISSUE TITLE
Add Support for new Firmware 0.2.0.0.71.0

### ISSUE THREAD

**Issue by hmersch** [MiSchroe/ioBroker.klf200#15]
New Firmware out  0.2.0.0.71.0 as released here: https://updates2.velux.com/
ioBroker Forum reports that this is not working with this adapter: https://forum.iobroker.net/viewtopic.php?f=24&t=15919&p=182768#p182768

Please add support for this Firmware.

ALL USERS: PLEASE DO NOT UPGRADE TO NEW FW VERSION!

**Comment by MiSchroe** [comment]
VELUX has opened their API for public use with the new firmware. Unfortunately, this API works completely different and a lot of work has to be done.

**Comment by volkerrichert** [comment]
any update?

**Comment by MiSchroe** [comment]
Currently, I don't have much spare time to work on this. I'm still working on finalizing the underlying library. I will have some spare time during August, so that I hope to finalize the underlying library. Change of the adapther should be much simpler, because I build the underlying library to provide a similar interface. Additionally, the setup of the box is simpler, because you don't need to define all the separate scenes anymore.

**Comment by volkerrichert** [comment]
ok. I adopt the klf script (https://forum.iobroker.net/topic/14312/adapter-für-velux-klf-200-interface/) to my needs (shuttercontrol). Not perfect and less flexible but seems to work. 

So don't stress yourself. 

Volker

**Comment by quaschi** [comment]
Hi any Update?

**Comment by volkerrichert** [comment]
I'm still using my script.

**Comment by Phil2877** [comment]
Hi, I also would be very interested in a update so I can use current Velux Firmeware with IO Broker.

**Comment by Garfonso** [comment]
Currently you can use it with fhem and use the fhem adapter.

**Comment by Phil2877** [comment]
> Currently you can use it with fhem and use the fhem adapter.

Thanks for this hint. I have set up a fhem Server and it does work. Only unsind scenes from the name drop down list doesn't work with the IO Broker. Selecting scenes via scene ID works fine. Do you have same issue? Any Idea why? Also tested this with a fhem app on iOS and there's the same problem. I can see the list of scenes but select doesn't start the scene.
Selecting a scene from drop down list on fhem web portal itself works fine again...

**Comment by Garfonso** [comment]
I did never test that feature, tbh. I mostly use the percent value for opening my roof window.

**Comment by klein0r** [comment]
@MiSchroe How is the progress on this issue? Maybe I can support you

**Comment by MiSchroe** [comment]
I'm nearly finished. You could help on testing. The current development happens in the [newVeluxAPI](https://github.com/MiSchroe/ioBroker.klf200/tree/newVeluxAPI) branch.
Code review, escpecially looking for memory leaks would be nice.

What currently works:
- Connecting to the KLF-200 and reading products, scenes, groups
- Controlling products, scenes, groups by setting the targetPosition
- Updates to the states even when operated with an original remote control

I'm facing some connection problems that lead to reconnects every now and then and I'm not quite sure where they come from.

**Comment by MSteuter** [comment]
> I'm nearly finished. You could help on testing. The current development happens in the [newVeluxAPI](https://github.com/MiSchroe/ioBroker.klf200/tree/newVeluxAPI) branch.
> Code review, escpecially looking for memory leaks would be nice.

Hi, I am absolutely new to iobroker and klf200 but I am interested in testing, if you need more users.
My KLF200 is brand new and with the latest firmware version.

Do you have instructions how to install your adapter?
I have installed klf-200-api in node_modules and copied your branch code in iobroker.klf200. First problem was "cannot find start file!". After copying the whole "build" directory to the adapters root and changing package.json it started.

But now i have the error:
Terminated (ADAPTER_REQUESTED_TERMINATION): Login to KLF-200 device at 192.168.x.y failed.
instance system.adapter.klf200.0 terminated by request of the instance itself and will not be restarted, before user restarts it.

KLF200 LAN settings are correct. Static IP reachable by ping, telnet on 51200 is connected.
I tried the iobroker settings: IP, http://IP, http://IP:80 and IP:51200. Nothing worked for me.
Any hints? Thanks in advance.

**Comment by MiSchroe** [comment]
@MSteuter It should work if you type in the IP address or the DNS name of the KLF-200, e.g. `velux-klf-1234`. If you use the DNS name, you may have to add some domain suffix, e.g. if you have a FritzBox you have to use `velux-klf-1234.fritz.box`. Don't use any http or port numbers. It's not http and the port number is constant.

If you still have issues, please provide the log of ioBroker and what you have changed in the package.json.

BTW: You should go into the iobroker.klf200 folder and run the command `npm install --production` to install the dependencies that the adapter needs to work.

I'm nearly finished and will provide a new version in a few days, which would make installing a little bit easier.

**Comment by MSteuter** [comment]
> I'm nearly finished and will provide a new version in a few days, which would make installing a little bit easier.

@MiSchroe Got the current github version running.
Installation via `iobroker url https://github.com/MiSchroe/ioBroker.klf200/tarball/newVeluxAPI`
And the web password is NOT the API password. Used the password on the sticker and it works like a charm.

Thanks.

**Comment by DcFamas** [comment]
Same here, I installed v.1.0.0 insert the dns of my fritzbox (velux.fritz.box) and typed the password for the "wifi". When I use my own web password (velux123 before) I get the error:

`

host.ioBroker | 2020-06-16 13:24:45.776 | info | Do not restart adapter system.adapter.klf200.0 because desired by instance
-- | -- | -- | --
host.ioBroker | 2020-06-16 13:24:45.774 | error | instance system.adapter.klf200.0 terminated by request of the instance  itself and will not be restarted, before user restarts it.
klf200.0 | 2020-06-16 13:24:45.248 | info | (28654) Terminated (ADAPTER_REQUESTED_TERMINATION): Login to KLF-200 device at velux.fritz.box failed.
klf200.0 | 2020-06-16 13:24:40.924 | info | (28654) Host: velux.fritz.box
klf200.0 | 2020-06-16 13:24:40.822 | info | (28654) starting. Version 1.0.0 in /opt/iobroker/node_modules/iobroker.klf200, node: v12.18.0, js-controller: 3.1.4
host.ioBroker | 2020-06-16 13:24:39.016 | info | instance system.adapter.klf200.0 started with pid 28654

`

**Comment by sgoelz** [comment]
Thanks for the great work @MiSchroe !

For me it's also working fine with the ip address and the wifi password. If there are any open use cases to test, i could help.

**Comment by klein0r** [comment]
I've tested the new version and everything works fine! Thanks a lot 👍 
When do you plan to publish a new npm release for the latest repository?

**Comment by MiSchroe** [comment]
There are still some unhandled exceptions that I have to fix.

**Comment by klein0r** [comment]
Let me know if I can support you. I'm currently recording a new YouTube Video about the Velux interface and how to integrate it into ioBroker with your adapter.

**Comment by MiSchroe** [comment]
@klein0r 

> I've tested the new version and everything works fine! Thanks a lot 👍
> When are you going to publish a new npm release for the latest repository?

I have published the new release to npm and it should be available in the latest repository by tomorrow, I guess.

I have implemented password encryption, so when you install the latest version, you have to type in the password once again.

**Comment by klein0r** [comment]
Sounds awesome 👍  Thanks a lot
