### ISSUE TITLE
limitationMax?

### ISSUE THREAD

**Issue by Garfonso** [MiSchroe/ioBroker.klf200#47]
Hi,

thank you very much for adding support for the new Firmware/API. 

Till now I did use fhem (and fhem connector in ioBroker) to control my KLF device. I switched now to your adapter. I control a velux roof window with it that is also equipped with a rain sensor. fhem did show me a value for "limitationMax" in the states. With no rain this was set to 100 and with rain it was reduced to something like 5. In this way I could detect rain.
Is it possible to receive this value in the adapter, too?

Not sure if that makes sense at all.

Garfonso

**Comment by psychos4** [comment]
Wenn man den Status vom Regensensor abrufen könnte, wäre echt praktisch. 
Wie siehts zeitlich mit dem geplanten Update aus?

Ansonsten - ein großartiger Adapter! Danke für deine Arbeit!
