### ISSUE TITLE
Documentation states that the web logon password should be used while only WiFi password works

### ISSUE THREAD

**Issue by jens-maus** [MiSchroe/ioBroker.klf200#52]
**Describe the bug**  
In the current documentation it is stated that for connecting/configuring the klf200 adapter to connect to the KLF200 system the web logon password should be used (see https://github.com/MiSchroe/ioBroker.klf200/blame/master/docs/de/ReadMe.md#L71-L73). It, however, took me quite a while to identify that rather than using the "Web logon" (standard 'velux123' or a self defined webui password) the WIFI Password stated on the back of the KLF200 box is the one that has to be used.

While I don't know if this might be only the case for the latest firmware (I am using 0.2.0.0.71.0) and in previous versions also the web logon password worked, it is nevertheless the case for my klf200 gateway that I have to use the hard encoded WiFi Password printed on the back side of the KLF200 gateway rather than the web logon password.

**Comment by ThoSt81** [comment]
I can confirm this. The web logon password used to work but stopped at some point (not sure when) and now I can only get it to work using the WiFi password.

**Comment by s7urmi** [comment]
Can confirm aswell. Maybe it has to do with the fact that i changed the default IP-Address of the gateway?
The documentation also states to use the same hostname as for the web-logon(which is klf-200.velux via WiFi on mine) but that doesn't work in any way for me neither with the web-password nor the wifi-password. 
Only combination that works for me is the configured ip-address with wifi-password
