### ISSUE TITLE
crashes after installation

### ISSUE THREAD

**Issue by gmantoha** [MiSchroe/ioBroker.klf200#54]
**Describe the bug**  
The adapter crashes after installation.
The log shows TypeError: _b.off is not a function

**To Reproduce**  
After installed to iobroker and configured IP and Password.

**Expected behavior**  
It should not crash.

**Screenshots & Logfiles**  
![image](https://user-images.githubusercontent.com/12948141/96625752-de00db00-130e-11eb-8131-be33fb8d78da.png)

**Versions:**  
 - Adapter version: 1.0.1
 - JS-Controller version: 2.1.1
 - Node version: v 8.15.0
 - Operating system: Docker on Synology

**Additional context**  
-

**Comment by MiSchroe** [comment]
You need at least Node version 10.x.
