### ISSUE TITLE
Adapter crashes every 2-3 days

### ISSUE THREAD

**Issue by jroegner** [MiSchroe/ioBroker.klf200#59]
**Describe the bug**  
The Adapter stops working every 2-3 days.
Restart of adapter doesn't help. The KLF200 Gateway has to be powered off and on.
Cron pattern in the adapter is set. Also a reload of the adapter every day is set via cron job

**To Reproduce**  
Happens ever 2-3 days after restart of KLF200

**Expected behavior**  
The adapter should stay online in a working state

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.
![image](https://user-images.githubusercontent.com/66469064/113414901-4d025580-93be-11eb-9619-efdf67fb01bc.png)

**Versions:**  
 - Adapter version: 1.0.1
 - JS-Controller version: 3.2.16
 - Node version: v12.21.0 
 - Operating system: linux

**Additional context**  
KLF200 is on firmware 0.2.0.0.71.0

**Comment by MiSchroe** [comment]
Do you have any other programs, systems, etc. that connect to the same KLF200? The KLF200 doesn't support more than two simultanous connections.

It seems, that your KLF200 reaches some kind of "stall" state. It happens to me maybe 2-3 times a year and I even don't use the automatic reboot option.
Try to disable the adapter for 3 or 4 days. Does it connect after enabling it again? If no, then there is a problem with your KLF200.

What is your usage scenario? The KLF200 shouldn't be flooded with parallel commands. Try to use scenes or groups instead, e.g. if you want to open two windows in parallel make a group and open the group.

**Comment by jroegner** [comment]
Hi,
no other programs or systems connect to the KLF200.
Disabling the adapter didn't help. Every 2-3 days the adapter becomes red and has to be restarted cold.
I don't use groups or scenes. There are only two shutters. These objects are used in yahka for controlling the shutters in HomeKit.

**Comment by jroegner** [comment]
Update:
When I switch off the adapter for a few hours after it stopped working, it's working again with switching on the adapter. (Without cold reboot of the KLF)
