### ISSUE TITLE
Question. Rain sensor feedback?

### ISSUE THREAD

**Issue by s31teg** [MiSchroe/ioBroker.klf200#60]
**Is your feature request related to a problem? Please describe.**
Hello

I don't have the KLF-200 yet thus I'm asking the question sorry.

In the documentation it states '    2. Your window will start to move to 40% opening level. (If it's not blocked, e.g. by the rain sensor.)'

Does the window provide feedback of position or is it just told to go to that position. So I would be able to add logic if the window failed to moved due to rain?

**Describe the solution you'd like**
As above

**Describe alternatives you've considered**
As above

**Additional context**
Thanks in advance. Great work on this connector! :)

**Comment by MiSchroe** [comment]
Yes, in case of a window you will get feedback of the status of the operation (e.g. if it succeeded or if it failed) and also the current position. For your case you could check for the status other than OK and then do further steps.

**Comment by s31teg** [comment]
Perfect. Thanks for getting back to me so quickly!
