### ISSUE TITLE
new Datapoint "open/close"

### ISSUE THREAD

**Issue by DcFamas** [MiSchroe/ioBroker.klf200#61]
Hey Michael,
is it possible that you implement a datapoint like the "stop" action for "open" and "close"?
So that when you send true to the datapoint "open" the blind will get the 100% and open? 

Thank you and best regards! :)
DcFamas

**Comment by MiSchroe** [comment]
I would like to keep the interface as less specific as possible. The KLF200 supports all kind of devices, therefore "open" and "close" would work for windows and blinds, but not for lights, fans, etc.

If you need that specific functionality, you could use the script adapter (it should be possible with Blockly) to mimic that functionality or you could use a very basic NodeRED flow for it.

Currently, I don't see the difference in setting a value to 100% or 0% in comparison to setting a value to true.

What is your specific use case that can't be done with the current implementation?

**Comment by DcFamas** [comment]
Hey Michael,
thanks for the lightspeedlike answer. :)

I know that I could realise this case with an script or in node-red. In my case I had an conversation with another developer. He told me that adapter in ioBroker use a standardized value of objects. For example the shelly adapter uses boolean to turn lights on and off. The mqtt api from shelly only supports "on" and "off" strings. So the developer there changed the on/off values to boolean that it fits in the ioBroker environment.

I have to use the objects in iQontrol. It would be easier to work with boolean, because this developer uses true/false for open and close. 

My thought was just a suggestion, I can understand that you want to keep the api by velux clean. Isn't there an option to recognize that the product is a blind/window and add the additional datapoints?

Btw. I'm really grateful for the adapter. For about an year it is working like a charm for me. :)

**Comment by MiSchroe** [comment]
So, what would be the expected behaviour?

I guess:
- set open to true -> set value to 100% and close to false
- set close to ture -> set value to 0% and open to false
- set value to 100%/0% -> set open/close like above
- set value to greater than 0% -> I would assume open = true, close = false

**Comment by DcFamas** [comment]
Hey Michael,
it would be:
- press button "close" -> set targetPosition to 100%
- press button "open" -> set targetPosition to 0%

I think for the most participants it is enough to have these datapoints.

Here is a screenshot of the shelly datapoints:
![grafik](https://user-images.githubusercontent.com/35306967/115550983-c2b95d00-a2aa-11eb-83ae-e56b60873c06.png)

Best regards! :)

**Comment by MiSchroe** [comment]
Can be implemented using alias in ioBroker.
