### ISSUE TITLE
"targetPosition" not reacting to MQTT-client changes

### ISSUE THREAD

**Issue by docpayce** [MiSchroe/ioBroker.klf200#68]
**Describe the bug**  
When changing "targtPosition" of any product via e.g. API ("http://<ipadress>:8087/set/klf200.0.products.3.targetPosition?value=100&prettyPrint") everything works as intended. When trying the same via the adapter "mqtt-client" the value of the object is changed in the iobroker GUI ("tagetPosition" is updated to the new value) but the command is not executed, i.e. the position of the roller/shader will not start to change.

**To Reproduce**  
1. Setup MQTT broker if not available yet (e.g. via adapter "mqtt" localhost)
2. Add adapter mqtt-client if necessary
3. Change settings of object "targetPosition" to both publish and subscribe to an appropriate MQTT topic, e.g. "klf200/0/products/0/targetPosition"
4. Publish a random value on topic "klf200/0/products/0/targetPosition"
5. The value is updated but no movement executed

**Expected behavior**  
One would expect the shader/roller to start moving with any change in "targetPosition" no matter the source of change.

**Screenshots & Logfiles**  
Screenshot 1: Everything normal, currentPosition = targetPosition as intended
![Clipboard01](https://user-images.githubusercontent.com/13950820/122399840-71aca900-cf7b-11eb-8a88-46a4e84ea7de.png)

Screenshot 2: After updating targetPosition to a random value via MQTT publish, the currentPosition will not change, as there is no movement happening
![Clipboard02](https://user-images.githubusercontent.com/13950820/122399846-72453f80-cf7b-11eb-8d55-166106097162.png)

**Versions:**  
 - Adapter version: 1.0.1
 - JS-Controller version: 3.2.16
 - Node version: <node-version> 12.22.1
 - Operating system: Raspberry Pi OS Lite 5.10

**Comment by MiSchroe** [comment]
Works for me if setting of targetPosition is only checked at "subscribe". Works sometimes somehow if "published" is selected, too.
