### ISSUE TITLE
KLF 200: Current Position – Wert im Trigger falsch

### ISSUE THREAD

**Issue by Automatisierer0** [MiSchroe/ioBroker.klf200#69]
Ich habe einen Trigger für die Current Poition.
+++++++++  Screenshot: Objekt_Current Position.jpg+++++++++
![Objekt_Current Position](https://user-images.githubusercontent.com/88152701/127784184-8181415c-da1e-4a36-83fd-679148a64293.jpg)

Der Trigger ist in Blockly geschrieben:
+++++++++  Screenshot: Trigger Current Position.jpg+++++++++
![Trigger Current Position](https://user-images.githubusercontent.com/88152701/127784191-f19c6a1d-73c5-4b45-91e3-d1f0dc74effc.jpg)

Das Verhalten ist OK, wenn ich ein Fenster aufmache und warte bis es offen ist. Wie man im Screenshot erkennt, sendet der KLF200, wenn das Fenster vollständig geöffnet ist im Trigger der richtigen Wert Current Position = 100
+++++++++  Screenshot Fenster Aufmachen -- mit Kommentar.jpg+++++++++
![Screenshot Fenster Aufmachen -- mit Kommentar](https://user-images.githubusercontent.com/88152701/127784198-3daa08fd-2070-4177-868f-7db5290bff28.jpg)

**Hier der Fehlerfall:**
Das Fenster wird wie im obigen Fall geöffnet, aber während des Öffnungsvorgangs wird es wieder geschlossen. Es ist hier im Trigger für die Current Position kein richtiger Wert! 
(Verdacht: Es schaut so aus als wäre es ein Nullpointer)
+++++++++  Screenshot Zumachen während Aufmachen läuft -- mit Kommenar.jpg+++++++++
![Screenshot Zumachen während Aufmachen läuft -- mit Kommenar](https://user-images.githubusercontent.com/88152701/127784202-e299a17e-43c5-4a46-a485-345e551f8428.jpg)

**Comment by MiSchroe** [comment]
Wenn der aktuelle Befehl durch einen anderen Befehl überschrieben wird, z.B. wenn man das Stop-Kommando sendet, dann wird zwischendrin für den alten Befehl eine Kommando-Ende Nachricht gesendet mit dem Feld StatusReply = 29 (Command Overruled = Befehl überschrieben). In dieser Nachricht befindet sich für die aktuelle Position ein ungültiger Wert, welchen ich entsprechend abfange und daher der Prozent-Wert auf NULL gesetzt wird. Durch den zweiten Befehl wird jedoch, wenn dieser abgeschlossen ist, wiederum eine gültige Position gesendet.

In Blockly kann man das Problem mit einer gezielten Abfrage auf ungleich NULL umgehen:
![image](https://user-images.githubusercontent.com/14166812/157732526-0e04e303-57b7-481e-81a1-ca77d076c5d0.png)

Der Wert ist daher nicht falsch, sondern zwischendurch kurzfristig nicht bekannt, was grundsätzlich eine gültige Aussage ist.
