### ISSUE TITLE
KLF 200: Current Position – Wert ist falsch

### ISSUE THREAD

**Issue by Automatisierer0** [MiSchroe/ioBroker.klf200#71]
**Achtung:** Dies ist eine **andere Fehlermeldung** als die Fehlermeldung ISSUE #69: “KLF 200: Current Position – Wert im Trigger falsch“

1.	Ich öffne das Fenster mit der VELUX-Bedienung auf 29 Prozent.
++++++++++++++++ Screenshot: VELUX Bedienung auf 29.jpg++++++++++++++++++
![Bedienung auf 29](https://user-images.githubusercontent.com/88152701/130280982-22745338-54af-4e60-8dbf-84fa8a7ab197.jpg)

2.	Wenn das den Öffnungszustand 29% erreicht ist in den Objekten die currentPosition wie erwartet 29
++++++++++++++++ Screenshot: Objektwert currentPosition ist 29.jpg ++++++++++++++++++
![Objektwert currentPosition ist 29](https://user-images.githubusercontent.com/88152701/130281078-364addef-b226-463e-9240-b0c066a681e5.jpg)

3.	Wenn der Wert 29% erreicht ist, triggert der Trigger STATUSÄNDERUNG
Der Trigger ist in Blockly geschrieben:
+++++++++  Screenshot: Blockly Script.jpg+++++++++
![Blockly Script](https://user-images.githubusercontent.com/88152701/130281109-a9597c35-e1b9-40a1-b93c-d1216c07ecd0.jpg)

Wenn im Trigger der Status den Wert 5 hat (d.h. DONE) lese ich nun im Trigger die CurrentPosition ein.
**Fehler:** Es wird 0 eingelesen und nicht 29 (Teil 1 betrachten !)
+++++++++  Screenshot: Logbuch für 29 und 82 +++++++++
![Logbuch für 29 und 82](https://user-images.githubusercontent.com/88152701/130281963-5b40c574-2522-4bbe-a938-bb9eda747834.jpg)

4.	Jetzt startet der zweite Teil
5.	Ich öffne das Fenster mit der VELUX-Bedienung nun auf 82 Prozent.
++++++++++++++++ Screenshot: VELUX Bedienung auf 82.jpg++++++++++++++++++
![Bedienung auf 82](https://user-images.githubusercontent.com/88152701/130282166-066da291-f22c-49d3-ae21-337e899b1b2f.jpg)

6.	Wenn das den Öffnungszustand 82% erreicht ist in den Objekten die currentPosition wie erwartet 82
++++++++++++++++ Screenshot: Objektwert currentPosition ist 82.jpg ++++++++++++++++++

![Objektwert currentPosition ist 82](https://user-images.githubusercontent.com/88152701/130281322-bfcb8bd9-4c23-4215-90d3-ca7f2e106aab.jpg)

7.	Wenn der Wert 82% erreicht ist, triggert der Trigger STATUSÄNDERUNG
Wenn im Trigger der Status den Wert 5 hat (d.h. DONE) lese ich nun im Trigger die CurrentPosition ein.
++++++++  Screenshot: Logbuch für 29 und 82 +++++++++
![Logbuch für 29 und 82](https://user-images.githubusercontent.com/88152701/130281982-fd86662b-2fc2-4b9d-a8b8-a21670a0e6ab.jpg)

**Fehler:** Es wird 29 eingelesen und nicht 82.  29 ist der Wert von vorher !!! (Teil 2 betrachten !)

**Comment by MiSchroe** [comment]
Ich konnte das Problem nachvollziehen, leider ist das ein prinzipielles Problem in ioBroker, was ich nicht ändern kann.

Jeder Datenpunkt ist für sich genommen unabhängig von den anderen und muss jeweils einzeln geändert werden. Wenn das KLF200 eine Benachrichtigung zur geänderten Position sendet, ist in dieser Nachricht zwar alles enthalten, aber ich kann die verschiedenen Datenpunkte nicht gleichzeitig ändern, sondern das passiert in einer bestimmten Reihenfolge. Dabei ändere ich den Status als erstes, dann kommen die anderen Datenpunkte dran.

In deinem Fall läuft es dann so:

1. Die Benachrichtigung von der KLF200 über die geänderte Position wird empfangen.
2. Ich aktualisiere den Status, z.B. auf 5.
3. ioBroker prüft, wer alles über die Änderung des Datenpunktes informiert werden will und ruft nacheinander alle Skripte, Adapter, etc. auf, darunter ist dann auch dein Blockly-Skript.
4. Dein Skript reagiert auf die Änderung des Datenpunktes und läuft los.
5. Dein Skript fragt den Datenpunkt mit der Position ab, dieser ist aber noch nicht aktualisiert, daher bekommst du noch den alten Wert übermittelt.
6. Dein Skript ist fertig.
7. Mein Adapter aktualisiert nun die weiteren Datenpunkte.

Um das Problem bei dir zu lösen, gibt es zwei Möglichkeiten:
1. Du baust eine kurze Zeitverzögerung ein, bevor du den Wert der aktuellen Position abfragst. Das hat bei mir z.B. bereits mit 100ms geklappt, das muss man aber individuell ausprobieren.
2. Du baust dein Skript um, so dass der Trigger auf die Änderung der currentPosition reagiert und machst den Rest nur dann, wenn der Status-Wert = 5 ist (denn der wird vorher geändert ist somit schon richtig).
