### ISSUE TITLE
Weiteres Problem mit Current Position

### ISSUE THREAD

**Issue by Automatisierer0** [MiSchroe/ioBroker.klf200#72]
**Fehler 1:** 
Aus mir nicht bekannten Gründen hat der KLF200-Adapter in der Nacht einen Restart gemacht.
+++++++++++++++++ Screenshot: Restart Adapter +++++++++++++++++++++++
![Restart Adapter](https://user-images.githubusercontent.com/88152701/130319322-97291da2-5881-41c3-91ec-49a7eeab96f2.jpg)

**Fehler 2:**
Während dieses Restart-Prozesses wird der Trigger mit geänderten Status fehlerhafterweise gefeuert.
Hier das entsprechende Script:
+++++++++++++++++ Screenshot: Blockly Script +++++++++++++++++++++++
![Blockly Script](https://user-images.githubusercontent.com/88152701/130319338-28b02e31-ee9e-476e-ba63-2cf7feea915b.jpg)

Der Wert des Satus im Trigger ist fehlerhafterweise 255
+++++++++++++++++ Screenshot: Log Teil 1.mit Kommentar jpg +++++++++++++++++++++++
![Log Teil 1 mit Kommentar](https://user-images.githubusercontent.com/88152701/130319344-c9c4fdf6-46f7-424a-b542-5cfe112ee5b0.jpg)

Danach wird scheinbar der richtige Wert (5 = DONE) in den Status geschrieben (Wer das macht weiß ich nicht) und wieder der Trigger gefeuert.
Im Trigger lese ich die currentPosition aus und diese ist falsch.
Es wird NULL ausgelesen !
+++++++++++++++++ Screenshot: Log Teil 2.mit Kommentar jpg +++++++++++++++++++++++
![Log Teil 2 mit Kommentar](https://user-images.githubusercontent.com/88152701/130319348-48a571fc-e8e1-41d4-96e1-00664ec1a021.jpg)

**Comment by MiSchroe** [comment]
Siehe https://github.com/MiSchroe/ioBroker.klf200/issues/71#issuecomment-1065034262
