### ISSUE TITLE
Flüstermodus

### ISSUE THREAD

**Issue by bulwind** [MiSchroe/ioBroker.klf200#74]
Hallo Michael,

ist es möglich mit dem Adapter die Rollladen im Flüstermodus zu steuern? Ich habe unter KLF200 Weboberfläche Programme/Szenen erstellt und für diese Flüstermodus eingestellt. Bei der Ausführung aus KLF200 Oberfläche wird das auch so ausgeführt. Wenn aber im iobroker die Szene mit run gestartet wird, läuft die Steuerung im normalen Modus und nicht im Flüstermodus. Gibt es die Möglichkeit über JavaScript die Szene im Flüstermodus auszuführen?

Vielen Dank für deine tolle Arbeit!
Grüße, Andreas

**Comment by MiSchroe** [comment]
Ich habe in der Schnittstellendefinition nachgesehen: Ob eine Szene im Flüstermodus oder nicht ausgeführt werden soll, wird nicht mit der Szene gespeichert, auch wenn dies so in der Weboberfläche angeboten wird. Es kann allerdings grundsätzlich beim Ausführen der Szene ein Geschwindigkeitsparameter angegeben werden (Standard, langsam oder schnell). 

Dafür muss ich jedoch Anpassungen am Adapter vornehmen. Es müsste einen neuen Datenpunkt an der Szene geben, in dem ich die gewünschte Geschwindigkeit hinterlege. Beim Ausführen würde die Geschwindigkeit aus diesem Datenpunkt übernommen werden.

--------------

In English:

It is possible to set a scene in the web UI of the KLF200 to be run in silent mode. That setting is not stored as a parameter of a scene, so I can't read that setting from the KLF200. Instead I would implement a new data point where you could set the desired velocity for a scene and if you run the scene the velocity would be set according to the value of that data point.

**Comment by bulwind** [comment]
Die Lösung, wie du das beschrieben hast, kling gut. Wäre gleiches Vorgehen auch bei Steuerung einzelner Produkte möglich?
