### ISSUE TITLE
Flüstermodus RS100io

### ISSUE THREAD

**Issue by Basti189** [MiSchroe/ioBroker.klf200#77]
Hallo,

erstmal vielen Dank für deine Arbeit und das ich damit vom Onlinezwang eines gewissen Herstellers entkommen konnte.
Ich habe von Somfy den Rollladenmotor RS100io im Haus und kann diesen wunderbar über den Adapter steuern. Leider sehe ich keine Möglichkeit den Rollladen in seinem Flüstermodus fahren zu lassen. Das Feld Velocity ist nicht beschreibbar und wenn man es beschreibbar macht, hat dies keinen Einfluss auf die Fahrgeschwindigkeit. Ich nutze dieses Feature nur zu gern und würde es ungern aufgeben. Habe ich eine Möglichkeit übersehen?

Liebe Grüße
Basti

**Comment by dekatWin** [comment]
Ich hab ebenfalls versucht, wie Basti189, das Velocity Feld zu bearbeiten.
Jedoch würde ich gerne den Speed Modus nutzen, wirklich lauter ist das nicht aber dafür wesentlich schneller, was sehr hilfreich wäre bei größeren Fenstern. 

Gruß Dekat.
