### ISSUE TITLE
vertauschte Laufrichtung bei Velux Rolläden in Google Home über IOT-Adapter

### ISSUE THREAD

**Issue by apassler** [MiSchroe/ioBroker.klf200#95]
Ich habe eine ganze Reihe von VELUX-Dachflächenfenstern und bin sehr Begeistert von den Möglichkeiten des Adapters. Über Zigbee Schalter habe ich nun die Möglichkeit ohen die Velux-Pads meine Dachflächenfenster zu steuern. Auch die Steuerung über Scripe Blockly klappt wunderbar. Nun habe ich die Möglichkeit die Rolladen auch zusätzlich per Sprachsteuerung über Google Home su steuern. Die Verknüpfung zu IOT funktionierte auf Anhieb sehr gut. In der Home App wird der Zustand der Fenster sehr schön angezeigt. Leider gibt es da noch ein kleines Problem... 
Bei den VELUX-Rolläden ist die Prozentangabe zum Öffnungszustand vertauscht. 100% bedeutet, dass der Rolladen zu ist. Bei 70% ist er zu 30% offen. Ich muss so in meinen Sprachbefehlen zu den Rolläden umdenken und anstatt "öffenen" "schließem sagen". Ist es möglich targetPosition, bzw. currentPosition zu invertieren?

**Comment by MiSchroe** [comment]
Die Denkweise ist die, dass bei 100% der Rollladen zu 100% ausgefahren ist. In ioBroker lässt sich ein Alias einrichten, z.B. über den Alias Manager Adapter und über eine einfache Umrechnung (1 - val bzw. 100 - val, ich bin mir gerade nicht ganz sicher, wie der Prozentwert gespeichert wird) lässt sich der Wert umkehren.

Eine Umstellung des Verhaltens kann ich nicht durchführen, weil es dann bei allen anderen nicht mehr funktionieren würde.

**Comment by apassler** [comment]
Danke für den Tipp. 100 – val in der Alias App bei targetPosition ganz unten in den roten Feldern eingetragen hat funktioniert. Die Steuerung per IOT läuft nun einwandfrei.

Von: MiSchroe
Gesendet: Mittwoch, 1. Juni 2022 20:29
An: MiSchroe/ioBroker.klf200
Cc: apassler; Author
Betreff: Re: [MiSchroe/ioBroker.klf200] vertauschte Laufrichtung bei Velux Rolläden in Google Home über IOT-Adapter (Issue #95)

Closed #95 as completed.
